version: '3'

services:
  codestanding-ml:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile-cpu.dockerfile
    ports:
      - "8000-8030:8000-8030"
    volumes:
      - ..:/workspace
    command: sleep infinity