version: '3'

services:
  codestanding-ml:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ~/.gitconfig:$HOME/.gitconfig
      - ..:/workspace
    command: sleep infinity