version: '2.4'

services:
  codestanding-ml:
    runtime:
      "nvidia"
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile-gpu.dockerfile
    ports:
      - "8000-8499:8000-8499"
    volumes:
      - ..:/workspace
    command: sleep infinity